version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:80
    environment: 
    - env_value=cookies

  mysql-db:
    image: mysql:5.7.28
    ports:
    - 3308:3306
    environment: 
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=sportstore
  
  mysql-admin:
    image: adminer
    ports:
    - 8084:8080
